# Generated by Django 2.2.28 on 2024-01-31 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20240131_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='liks',
            new_name='likes',
        ),
    ]
